# Quiz 2-3: NumPy's and pandas

- In this quiz we will go over what we have learned about the NumPy and pandas packages.

- During and/or (necessarily) after you have finished this quiz be sure to commit and push using GitHub Desktop.

- Feel free to look back on the lecture/slides and use search engines for help.



# NumPy

## 1. Loading NumPy's
- Load the NumPy package.
    - Create a variable called `npm1` by loading in in the .npy file named `quiz2-3.npy`


In [1]:
#type your solution below this line:
import numpy as np

nmp1 = np.load('quiz2-3.npy') # this is numpys version of range

print(nmp1)


[[1 0 3 0]
 [2 2 2 0]
 [3 0 2 3]]


## 2. Create a NumPy

- Create a NumPy array variable named `nmp2` of the same dimensions as `nmp1` (3x4)
    - You can either create it manually and type in arbitrary numbers or you can use the `np.random.randint()` function and specify the correct `size=`

In [2]:
#type your solution below this line:

nmp2 = np.array([[ 0, 4, 1, 9], [7, 2, 12, 11] , [3, 4, 5, 6]])
nmp2

array([[ 0,  4,  1,  9],
       [ 7,  2, 12, 11],
       [ 3,  4,  5,  6]])

## 3. Show whether the elements of `nmp1` are greater than `nmp2`

In [3]:
#type your solution below this line:
nmp1 > nmp2

array([[ True, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

## 4. Add the two variables together.

- Add the variables together to make a new variable `nmp3`
    - Display `nmp3`

In [4]:
#type your solution below this line:
nmp3 = np.add(nmp1, nmp2)
print (nmp3)

[[ 1  4  4  9]
 [ 9  4 14 11]
 [ 6  4  7  9]]


## 5. Find the mean of `nmp3`.

In [5]:
#type your solution below this line:
# the mean for all levels

nmp3.mean()

6.833333333333333

## 6. Save `nmp3` as a file named `problem5`

In [6]:
#type your solution below this line:

np.save('problem5', nmp3)

# Panda dataframes and data wrangling

## 7. Create a dictionary and convert it to a panda.

 - Name your new dictionary `fam` in which lists three people in your family.

    - This will be a nested dictionary.
        - First list their names.
        - Then make another dictionary for each person which includes thier age, relationship and gender.
        - example:
        
                `myfamily={
                   "Name1": {
                     "age": x,
                     "relationship":'y',
                     "gender":'z' } 
                     }`
     - Convert this dictionary into a pandas dataframe variable named `myfamily`
     - Display your dataframe.


In [7]:
#type your solution below this line:
import pandas as pd

# Nested dictionary
fam = {
    'Lizwe' : {'age': ['24'], 'relationship': ['brother'], 'gender': ['male']},
    'Bessie': {'age': ['26'], 'relationship': ['sister'], 'gender': ['male']},
    'Tasha':{'age': ['32'], 'relationship': ['sister'], 'gender': ['female']}
}

myfamily= pd.DataFrame(fam) # we can convert our dictionaries into neat panda dataframes
myfamily

Lizwe    Bessie     Tasha
age                [24]      [26]      [32]
relationship  [brother]  [sister]  [sister]
gender           [male]    [male]  [female]

## 8. Now transpose you dictionary to a more sensible format (each person is a row)
- Transposing the variable will not alone overwrite it.
    - Overwrite the `myfamily` variable with the transposed variable.
    - Display your updated panda dataframe.

In [8]:
#type your solution below this line:

myfamily = myfamily.transpose()
myfamily

age relationship    gender
Lizwe   [24]    [brother]    [male]
Bessie  [26]     [sister]    [male]
Tasha   [32]     [sister]  [female]

## 9. Save your transformed panda into a .csv file 
- Name the file `my_family`.

In [9]:
#type your solution below this line:

myfamily.to_csv('my_family.csv')

## 10. Make and edit a dataframe.
- ### A. Create a copy of `df` below (be sure to load the code chunck that includes `df`) named `df2` that does not impact the original dataframe when altered.
- ### B. Add a new column `E` to the dataset which is equal to 'yes' if column `B` is less than 50 and 'no' otherwise. Display your updated dataframe.
- ### C. Make all the column names (`A`,`B`,`C`,`D`,`E`) lowercase. Display your updated dataframe.

In [10]:
import numpy as np
import pandas as pd 
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD')) #np.random.randint(start.value, end.value., size = (#rows, #columns))
df

A   B   C   D
0    2  29  64  24
1   87   4  88  42
2   35  20  60  90
3   87  68  81   2
4   30  18  59  16
..  ..  ..  ..  ..
95  36  57   7  75
96  95   4  43  21
97  68  72  32   6
98  81  78  36  57
99  25  75  83  39

[100 rows x 4 columns]

In [11]:
#type your solution to A below this line:
df2 = df.copy()
df2

A   B   C   D
0    2  29  64  24
1   87   4  88  42
2   35  20  60  90
3   87  68  81   2
4   30  18  59  16
..  ..  ..  ..  ..
95  36  57   7  75
96  95   4  43  21
97  68  72  32   6
98  81  78  36  57
99  25  75  83  39

[100 rows x 4 columns]

In [19]:
#type your solution to B below this line:
df['e']if x<50: return 'Yes'; else:return 'No'
        
df2.update(e)
print(df2)


SyntaxError: invalid syntax (<ipython-input-19-cc3a589b2a44>, line 2)

In [14]:
#type your solution to C below this line:

df2.columns = map(str.lower, df2.columns)
df2

a   b   c   d
0    2  29  64  24
1   87   4  88  42
2   35  20  60  90
3   87  68  81   2
4   30  18  59  16
..  ..  ..  ..  ..
95  36  57   7  75
96  95   4  43  21
97  68  72  32   6
98  81  78  36  57
99  25  75  83  39

[100 rows x 4 columns]