# Activty 2-3

- In this activity we will go over what we have learned about the NumPy and pandas modules.

## 1. Loading NumPy's

    - Load the NumPy module.
    - Create a variable called nmp1 by loading in in the .npy file named `activity2-3.npy`


In [2]:
import numpy as np
import pandas as pd
nmp1 = np.load('quiz2-3.npy')

nmp1

array([[1, 0, 3, 0],
       [2, 2, 2, 0],
       [3, 0, 2, 3]])

## 2. Create a NumPy

    - Create a NumPy array variable named `nmp2` of the same dimensions as `nmp1` (3x4)
        - You can either create it manually and type in arbitrary numbers or you can use the `np.random.randint()` function and specify the correct `size=`

In [3]:
 nmp2 = np.random.randint(10, size=(3, 4))
    
nmp2

array([[1, 2, 2, 5],
       [1, 2, 4, 5],
       [7, 3, 4, 6]])

## 3. Show whether the elements of `nmp1` is greater than `nmp2`

In [4]:
nmp1 > nmp2

array([[False, False,  True, False],
       [ True, False, False, False],
       [False, False, False, False]])

## 4. Add the two variables together and create a new variable named `nmp3`

    -Print (or simply type the variable name) `nmp3`

In [5]:
nmp3 = nmp1 + nmp2

nmp3

array([[ 2,  2,  5,  5],
       [ 3,  4,  6,  5],
       [10,  3,  6,  9]])

## 5. Find the mean of `nmp3`.

In [6]:
nmp3.mean()

5.0

## 6. Save `nmp3` as a file named `problem5`

In [7]:
np.save('problem5', nmp3)

## 7. Create a dictionary and convert it to a panda.

    - named `fam` which lists three people in your family.

    - This will be a nested dictionary.
        - First list their names.
        - Then make another dictionary for each person which includes thier age, relationship and gender.
        - example:
        
                `myfamily={
                   "Name1": {
                     "age": x,
                     "relationship":'y',
                     "gender":'z' } 
                     }`
     - Convert this dictionary into a pandas dataframe variable named `myfamily`
     - Display your dataframe.


In [8]:
fam = {
  "Jordan" : {
             "age" : 34,
    "relationship" : 'partner',
           "gender": 'male'
  },
  "Ray" : {
             "age" : 53,
    "relationship" : 'Dad',
           "gender": 'male'
  },
  "Jesse" : {
             "age" : 11,
    "relationship" : 'brother',
           "gender": 'male'
  }
}


myfamily = pd.DataFrame(fam)
myfamily

Jordan   Ray    Jesse
age                34    53       11
relationship  partner   Dad  brother
gender           male  male     male

## 8. Now transpose you dictionary to a more sensible format (each person is a row)
    - Transposing the variable will not alone overwrite it.
    - Overwrite the `myfamily` variable with the transposed variable

In [9]:
myfamily = myfamily.T
myfamily

age relationship gender
Jordan  34      partner   male
Ray     53          Dad   male
Jesse   11      brother   male

## 9. Load in a dataset using this web address: https://domlockett.github.io/website/Population.csv
    - Import the pandas module

    - Name the dataset `pop`
    
    - print the first 5 rows in pop.

In [10]:
import pandas as pd
pop = pd.read_csv('https://domlockett.github.io/website/Population.csv')
pop.head()

Time Time Code    Country Name Country Code  \
0  1990    YR1990     Afghanistan          AFG   
1  1990    YR1990         Albania          ALB   
2  1990    YR1990         Algeria          DZA   
3  1990    YR1990  American Samoa          ASM   
4  1990    YR1990         Andorra          AND   

   Population, total [SP.POP.TOTL]  
0                       12412308.0  
1                        3286542.0  
2                       25758869.0  
3                          47347.0  
4                          54509.0

## 10. Make and edit a dataframe.
- ### A. Create a copy named `df2` that does not impact the original dataframe when altered.
- ### B. Add a new column `E` to the dataset which is equal to 'yes' if column `B` is less than 50 and 'no' otherwise. 
- ### C. Make all the column names (`A`,`B`,`C`,`D`,`E`) lowercase.

In [11]:
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD')) #np.random.randint(start.value, end.value., size = (#rows, #columns))
df

A   B   C   D
0   94  44  82  29
1   89  53  39  65
2    5  63  39  84
3   34  35  18  90
4   24   8  47  19
..  ..  ..  ..  ..
95  51  34  44  24
96  31  82   8  52
97  23  85  79  83
98  76  54  60  61
99   2  54  92  10

[100 rows x 4 columns]

In [12]:
#type your solution to A below this line:

df2 = df.copy()

In [13]:
#type your solution to B below this line:

df2['E'] = np.where(df['B'] < 50, 'yes','no')
df2

A   B   C   D    E
0   94  44  82  29  yes
1   89  53  39  65   no
2    5  63  39  84   no
3   34  35  18  90  yes
4   24   8  47  19  yes
..  ..  ..  ..  ..  ...
95  51  34  44  24  yes
96  31  82   8  52   no
97  23  85  79  83   no
98  76  54  60  61   no
99   2  54  92  10   no

[100 rows x 5 columns]

In [14]:
#type your solution to C below this line:

df2.columns = ['a','b','c','d','e']
df2


a   b   c   d    e
0   94  44  82  29  yes
1   89  53  39  65   no
2    5  63  39  84   no
3   34  35  18  90  yes
4   24   8  47  19  yes
..  ..  ..  ..  ..  ...
95  51  34  44  24  yes
96  31  82   8  52   no
97  23  85  79  83   no
98  76  54  60  61   no
99   2  54  92  10   no

[100 rows x 5 columns]